### ISSUE TITLE
Support Sass

### ISSUE THREAD

**Issue by wbyoung** [emmetio/livestyle-web#7]
Similar to #4, I think it'd be great to add support for Sass.

Any thoughts on how to go about doing this or what might be some of the challenges of supporting Sass?

I haven't taken a look at the code yet, but off hand I would imagine that some of the challenges would be:

 - Handling compiling since unlike CSS there could be multiple imported files related to the one associated with LiveStyle
 - Mapping changes in the browser inspector back to the right part of the Sass file

Any other thoughts on this?

**Comment by samarjeet27** [comment]
+1, it'll be great if it had support for sass.

**Comment by godot882** [comment]
+1 for sass and scss support

**Comment by sergeche** [comment]
http://livestyle.emmet.io/alpha/

**Comment by wbyoung** [comment]
@sergeche thanks!
